"""bybit

Revision ID: 3e04579c094b
Revises: 76f77e9d96ff
Create Date: 2025-10-15 22:39:53.533269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e04579c094b'
down_revision: Union[str, Sequence[str], None] = '76f77e9d96ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_secret', sa.String(), nullable=True, comment='API secret от биржи'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'api_secret')
    # ### end Alembic commands ###
