"""bybit2

Revision ID: 7728919689e4
Revises: 3e04579c094b
Create Date: 2025-10-16 00:41:44.242827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7728919689e4'
down_revision: Union[str, Sequence[str], None] = '3e04579c094b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('demo', sa.Boolean(), nullable=True, comment='Использование демо счета'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'demo')
    # ### end Alembic commands ###
