"""комментарий к миграции

Revision ID: 7e87fbb76b65
Revises: 
Create Date: 2025-10-06 22:49:56.881621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e87fbb76b65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Название монеты'),
    sa.Column('buy_usdt', sa.String(length=50), nullable=True, comment='На сколько USDT покупать монету если стоит в цикле'),
    sa.Column('cycle', sa.Boolean(), nullable=False, comment='Зацикливание монеты true / false на покупку и продажу'),
    sa.Column('price_buy', sa.Float(), nullable=True, comment='Курс первой покупки монеты'),
    sa.Column('last_price_buy', sa.Float(), nullable=True, comment='Курс последней покупки монеты'),
    sa.Column('order_buy_id', sa.Integer(), nullable=True, comment='ID ордера на покупку'),
    sa.Column('order_sell_id', sa.Integer(), nullable=True, comment='ID ордера на продажу'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_coin_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin')
    # ### end Alembic commands ###
