"""coin1

Revision ID: 87c71974fd9c
Revises: fc2604f2a136
Create Date: 2025-10-27 20:29:16.138234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c71974fd9c'
down_revision: Union[str, Sequence[str], None] = 'fc2604f2a136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('buy', sa.Integer(), nullable=False, comment='Количество закупок'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin', 'buy')
    # ### end Alembic commands ###
