"""coin1

Revision ID: 9272a77f1e8c
Revises: f92f29043648
Create Date: 2025-10-09 23:21:41.642928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9272a77f1e8c'
down_revision: Union[str, Sequence[str], None] = 'f92f29043648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coinslot', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID пользователя',
               existing_nullable=False)
    op.alter_column('coinslot', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата окончания слота',
               existing_nullable=True)
    op.drop_column('coinslot', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coinslot', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('coinslot', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата окончания слота',
               existing_nullable=True)
    op.alter_column('coinslot', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###
