"""user

Revision ID: b5a02f64e5d1
Revises: 
Create Date: 2025-10-08 23:30:32.785686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a02f64e5d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('telegram_id', sa.Integer(), nullable=False, comment='Телеграм id'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Статус суперпользователя'),
    sa.Column('password', sa.String(), nullable=True, comment='Хеш пароля'),
    sa.Column('api_key', sa.String(), nullable=True, comment='API key от биржи'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('coin',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Название монеты'),
    sa.Column('buy_usdt', sa.String(length=50), nullable=True, comment='На сколько USDT покупать монету если стоит в цикле'),
    sa.Column('cycle', sa.Boolean(), nullable=False, comment='Зацикливание монеты true / false на покупку и продажу'),
    sa.Column('price_buy', sa.Float(), nullable=True, comment='Курс первой покупки монеты'),
    sa.Column('last_price_buy', sa.Float(), nullable=True, comment='Курс последней покупки монеты'),
    sa.Column('order_buy_id', sa.Integer(), nullable=True, comment='ID ордера на покупку'),
    sa.Column('order_sell_id', sa.Integer(), nullable=True, comment='ID ордера на продажу'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_coin_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_coin_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin')
    op.drop_table('user')
    # ### end Alembic commands ###
