"""start2

Revision ID: fc2604f2a136
Revises: c8c7b664a88c
Create Date: 2025-10-23 22:24:36.434220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2604f2a136'
down_revision: Union[str, Sequence[str], None] = 'c8c7b664a88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('start', sa.Boolean(), nullable=False, comment='Запущена ли монета на торговлю'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin', 'start')
    # ### end Alembic commands ###
